# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
 projects: 'PGO.Identity.SignedSessions\PGO.Identity.SignedSessions.csproj'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'Release'
    projects: $(projects)
    nobuild: true
    versioningScheme: 'off'
    arguments: '--no-build'